version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s

  api:
    container_name: login_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my-app
    environment:
      DATABASE_URL: postgresql://postgres:123456@localhost:5432/
      PORT: 8080
      JWT_PASS: teste
    volumes:
      - .:/usr/src/app
    build:
      context: .

networks:
  my-app:
    driver: bridge
