version: "3.8"

services:
  api:
    container_name: login_api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my-login
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/api

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-login
    restart: always

networks:
  my-login:
    driver: bridge
