version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-app

  api:
    container_name: login_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    build:
      context: .

networks:
  my-app:
    driver: bridge
